version: "3.6"

services:
  mysql:
    image: mysql:8.0.42
    command: --sql_mode="NO_ENGINE_SUBSTITUTION" --log-bin-trust-function-creators=TRUE
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_USER=gosoline
      - MYSQL_PASSWORD=gosoline
      - MYSQL_ROOT_PASSWORD=gosoline
