app:
  env: dev
  name: consumer
  namespace: "{app.tags.project}.{app.env}.{app.tags.family}.{app.tags.group}"
  tags:
    project: gosoline
    family: how-to
    group: grp

stream:
  input:
    consumer:
      type: sqs
      target_queue_id: events

  output:
    todos:
      type:
        type: sqs
        queue_id: todos
