app:
  env: dev
  name: consumer
  namespace: "{app.tags.project}.{app.env}.{app.tags.family}.{app.tags.group}"
  tags:
    project: gosoline
    family: how-to
    group: grp

stream:
  input:
    consumer:
      type: file
      filename: events.json
