app:
  env: dev
  name: hello-world
  namespace: "{app.tags.project}.{app.env}.{app.tags.family}.{app.tags.group}"
  tags:
    project: gosoline
    family: how-to
    group: health-check

httpserver:
  // highlight-start
  health-check:
    path: /health
    port: 8090
  // highlight-end

kernel:
  // highlight-start
  health_check:
    timeout: 10s
    wait_interval: 1s
  // highlight-end
