app:
  env: dev
  name: hello-world
  namespace: "{app.tags.project}.{app.env}.{app.tags.family}.{app.tags.group}"
  tags:
    project: gosoline
    family: get-started
    group: grp

// highlight-start
log:
    level: info
    handlers:
        main:
            type: iowriter
            channels:
                metrics:
                    level: error
                http:
                    level: error
            formatter: console
            level: info
            timestamp_format: 15:04:05.000
            writer: stdout
// highlight-end
